# Generated by Django 5.2.9 on 2026-01-05 00:04

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerContactInfo",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique customer identifier (from main system)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Customer's first name", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Customer's last name", max_length=100),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary phone number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp number (may differ from phone)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        default="es",
                        help_text="ISO language code (e.g., 'es', 'en')",
                        max_length=10,
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True, help_text="Profile image URL", null=True
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this customer was synced from Core service",
                        null=True,
                    ),
                ),
                (
                    "sync_version",
                    models.IntegerField(
                        blank=True,
                        help_text="Version number from Core service for optimistic locking",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Contact Info",
                "verbose_name_plural": "Customer Contact Info",
                "db_table": "customer_contact_info",
            },
        ),
        migrations.CreateModel(
            name="ServicePhase",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Phase display name", max_length=100),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Lucide icon name (e.g., 'Calendar', 'Wrench')",
                        max_length=50,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, help_text="Sequence order in workflow"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this phase is active"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the phase",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Phase",
                "verbose_name_plural": "Service Phases",
                "db_table": "service_phases",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TallerChannelConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "taller_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique workshop identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "taller_name",
                    models.CharField(
                        blank=True,
                        help_text="Workshop display name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether email notifications are enabled",
                    ),
                ),
                (
                    "email_configured",
                    models.BooleanField(
                        default=False, help_text="Whether email is properly configured"
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether push notifications are enabled",
                    ),
                ),
                (
                    "push_configured",
                    models.BooleanField(
                        default=False, help_text="Whether push is properly configured"
                    ),
                ),
                (
                    "whatsapp_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether WhatsApp notifications are enabled",
                    ),
                ),
                (
                    "whatsapp_configured",
                    models.BooleanField(
                        default=False,
                        help_text="Whether WhatsApp is properly configured",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taller Channel Config",
                "verbose_name_plural": "Taller Channel Configs",
                "db_table": "taller_channel_configs",
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        db_index=True, help_text="Customer identifier", max_length=100
                    ),
                ),
                (
                    "endpoint",
                    models.TextField(
                        help_text="Push service endpoint URL", unique=True
                    ),
                ),
                (
                    "p256dh_key",
                    models.TextField(help_text="Public key for encryption (p256dh)"),
                ),
                ("auth_key", models.TextField(help_text="Authentication secret")),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Browser user agent for debugging",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this subscription is active"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time a notification was sent to this subscription",
                        null=True,
                    ),
                ),
                (
                    "failure_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of consecutive failures"
                    ),
                ),
            ],
            options={
                "verbose_name": "Push Subscription",
                "verbose_name_plural": "Push Subscriptions",
                "db_table": "push_subscriptions",
                "indexes": [
                    models.Index(
                        fields=["customer_id", "is_active"],
                        name="push_subscr_custome_8211cf_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Service type display name", max_length=100
                    ),
                ),
                ("icon", models.CharField(help_text="Lucide icon name", max_length=50)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this service type is active"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description", null=True
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent service type for subtypes",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtypes",
                        to="notifications.servicetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Type",
                "verbose_name_plural": "Service Types",
                "db_table": "service_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrchestrationConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[("clients", "Clientes"), ("staff", "Personal")],
                        help_text="Target audience (clients or staff)",
                        max_length=20,
                    ),
                ),
                (
                    "taller_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Optional: workshop-specific config (null for global)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this config is active"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this configuration",
                        null=True,
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        help_text="Service type this config applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orchestration_configs",
                        to="notifications.servicetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orchestration Config",
                "verbose_name_plural": "Orchestration Configs",
                "db_table": "orchestration_configs",
                "unique_together": {("service_type", "target", "taller_id")},
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Template display name", max_length=255),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Email subject line (optional for non-email channels)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "body",
                    models.TextField(help_text="Template content with {{variables}}"),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("push", "Push Notification"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        db_index=True,
                        help_text="Primary channel for this template",
                        max_length=20,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[("clients", "Clientes"), ("staff", "Personal")],
                        db_index=True,
                        help_text="Target audience (clients or staff)",
                        max_length=20,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a system default template",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is available for use",
                    ),
                ),
                (
                    "taller_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Optional: workshop-specific template",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        help_text="Required: service phase for this template",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="notifications.servicephase",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        help_text="Required: main service type for this template",
                        limit_choices_to={"parent__isnull": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="notifications.servicetype",
                    ),
                ),
                (
                    "subtype",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: specific subtype (for services with subtypes)",
                        limit_choices_to={"parent__isnull": False},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subtype_templates",
                        to="notifications.servicetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "db_table": "notification_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        db_index=True,
                        help_text="Customer identifier (owner)",
                        max_length=100,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        help_text="Vehicle manufacturer (e.g., 'Great Wall')",
                        max_length=100,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Vehicle model (e.g., 'Haval H6')", max_length=100
                    ),
                ),
                ("year", models.PositiveIntegerField(help_text="Manufacturing year")),
                (
                    "plate",
                    models.CharField(
                        db_index=True,
                        help_text="License plate number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "current_kilometers",
                    models.PositiveIntegerField(
                        default=0, help_text="Current odometer reading"
                    ),
                ),
                (
                    "last_service_date",
                    models.DateField(
                        blank=True, help_text="Date of last service", null=True
                    ),
                ),
                (
                    "next_service_kilometers",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Odometer target for next service",
                        null=True,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="Vehicle photo URL", null=True
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this vehicle was synced from Core service",
                        null=True,
                    ),
                ),
                (
                    "sync_version",
                    models.IntegerField(
                        blank=True,
                        help_text="Version number from Core service for optimistic locking",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "db_table": "vehicles",
                "indexes": [
                    models.Index(
                        fields=["customer_id"], name="vehicles_custome_a752bc_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceReminder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        db_index=True,
                        help_text="Customer identifier (for quick lookups)",
                        max_length=100,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("kilometers", "Kilómetros"),
                            ("date", "Fecha"),
                            ("both", "Ambos"),
                        ],
                        help_text="What triggers this reminder",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="What maintenance is needed"),
                ),
                (
                    "target_kilometers",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Odometer reading to trigger reminder",
                        null=True,
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        blank=True, help_text="Date to trigger reminder", null=True
                    ),
                ),
                (
                    "notify_via",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("email", "Email"),
                                ("push", "Push Notification"),
                                ("whatsapp", "WhatsApp"),
                            ],
                            max_length=20,
                        ),
                        default=list,
                        help_text="Channels to use for notification",
                        size=None,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("notified", "Notificado"),
                            ("completed", "Completado"),
                            ("overdue", "Vencido"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of the reminder",
                        max_length=20,
                    ),
                ),
                (
                    "notify_before_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Days before target_date to notify",
                        null=True,
                    ),
                ),
                (
                    "notify_before_km",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Km before target_kilometers to notify",
                        null=True,
                    ),
                ),
                (
                    "last_notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time a notification was sent",
                        null=True,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        help_text="Vehicle this reminder is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="notifications.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Reminder",
                "verbose_name_plural": "Maintenance Reminders",
                "db_table": "maintenance_reminders",
            },
        ),
        migrations.CreateModel(
            name="CustomerChannelPreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("push", "Push Notification"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        help_text="Notification channel",
                        max_length=20,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the customer has enabled this channel",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Order of preference (1 = highest priority)",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        db_column="customer_id",
                        help_text="Customer this preference belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_preferences",
                        to="notifications.customercontactinfo",
                        to_field="customer_id",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Channel Preference",
                "verbose_name_plural": "Customer Channel Preferences",
                "db_table": "customer_channel_preferences",
                "ordering": ["priority"],
                "unique_together": {("customer", "channel")},
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("appointment_scheduled", "Cita Agendada"),
                            ("vehicle_received", "Vehículo Recibido"),
                            ("repair_started", "Reparación Iniciada"),
                            ("quality_check", "Control de Calidad"),
                            ("vehicle_ready", "Vehículo Listo"),
                            ("maintenance_reminder", "Recordatorio de Mantenimiento"),
                            ("maintenance_overdue", "Mantenimiento Vencido"),
                            ("custom", "Personalizado"),
                        ],
                        db_index=True,
                        help_text="What triggered this notification",
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("push", "Push Notification"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        db_index=True,
                        help_text="Channel used for delivery",
                        max_length=20,
                    ),
                ),
                (
                    "recipient_id",
                    models.CharField(
                        db_index=True,
                        help_text="Customer/staff identifier",
                        max_length=100,
                    ),
                ),
                (
                    "recipient_address",
                    models.CharField(
                        help_text="Email address, phone number, or push endpoint",
                        max_length=255,
                    ),
                ),
                (
                    "template_id",
                    models.UUIDField(
                        blank=True, help_text="Template used (if any)", null=True
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True,
                        help_text="Template name for reference",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject line (for email)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "body_preview",
                    models.TextField(
                        blank=True,
                        help_text="First 500 chars of rendered body",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("queued", "En cola"),
                            ("sent", "Enviado"),
                            ("delivered", "Entregado"),
                            ("read", "Leído"),
                            ("bounced", "Rebotado"),
                            ("failed", "Fallido"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current delivery status",
                        max_length=20,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was sent",
                        null=True,
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, help_text="When delivery was confirmed", null=True
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was read",
                        null=True,
                    ),
                ),
                (
                    "error_reason",
                    models.TextField(
                        blank=True, help_text="Error message if failed", null=True
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        help_text="Error code for categorization",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of retry attempts"
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=3, help_text="Maximum retry attempts allowed"
                    ),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True, help_text="Scheduled time for next retry", null=True
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        default=dict,
                        help_text="Original context for template rendering and channel priority",
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Groups related notifications from same event",
                        null=True,
                    ),
                ),
                (
                    "parent_log",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to original notification if this is a fallback",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fallback_attempts",
                        to="notifications.notificationlog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "db_table": "notification_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "channel"],
                        name="notificatio_status_0dacf4_idx",
                    ),
                    models.Index(
                        fields=["recipient_id", "-created_at"],
                        name="notificatio_recipie_f0aafd_idx",
                    ),
                    models.Index(
                        fields=["correlation_id"], name="notificatio_correla_5e75a4_idx"
                    ),
                    models.Index(
                        fields=["sent_at"], name="notificatio_sent_at_85d1ed_idx"
                    ),
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="notificatio_status_44e75a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PhaseChannelConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("push", "Push Notification"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        help_text="Notification channel",
                        max_length=20,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether notifications are enabled for this phase/channel",
                    ),
                ),
                (
                    "orchestration_config",
                    models.ForeignKey(
                        help_text="Parent orchestration config",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phase_configs",
                        to="notifications.orchestrationconfig",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template to use for this notification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase_configs",
                        to="notifications.notificationtemplate",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        help_text="Service phase this applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_configs",
                        to="notifications.servicephase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phase Channel Config",
                "verbose_name_plural": "Phase Channel Configs",
                "db_table": "phase_channel_configs",
                "unique_together": {("orchestration_config", "phase", "channel")},
            },
        ),
        migrations.AddIndex(
            model_name="notificationtemplate",
            index=models.Index(
                fields=["channel", "target"], name="notificatio_channel_6509c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationtemplate",
            index=models.Index(
                fields=["taller_id", "channel"], name="notificatio_taller__d1d87f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationtemplate",
            index=models.Index(
                fields=["is_active", "channel"], name="notificatio_is_acti_14a94b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationtemplate",
            index=models.Index(
                fields=["service_type", "phase", "channel"],
                name="notificatio_service_7d4444_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationtemplate",
            index=models.Index(
                fields=["service_type", "subtype", "phase"],
                name="notificatio_service_e078bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancereminder",
            index=models.Index(
                fields=["status", "target_date"], name="maintenance_status_ec51c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancereminder",
            index=models.Index(
                fields=["customer_id", "status"], name="maintenance_custome_22baac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancereminder",
            index=models.Index(
                fields=["vehicle", "status"], name="maintenance_vehicle_c003c3_idx"
            ),
        ),
    ]
