# Generated by Django 5.2.9 on 2026-01-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicephase",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique identifier for API lookups (e.g., 'phase-schedule')",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique identifier for API lookups (e.g., 'mantenimiento-preventivo')",
                null=True,
                unique=True,
            ),
        ),
    ]
