# Generated by Django 5.2.9 on 2026-01-10 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_add_slug_to_service_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customercontactinfo",
            name="avatar_url",
        ),
        migrations.RemoveField(
            model_name="customercontactinfo",
            name="preferred_language",
        ),
    ]
