# Generated by Django 5.2.9 on 2026-01-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_remove_customercontactinfo_avatar_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicephase",
            name="slug",
            field=models.SlugField(
                help_text="Unique identifier for API lookups (e.g., 'phase-schedule')",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="servicetype",
            name="slug",
            field=models.SlugField(
                help_text="Unique identifier for API lookups (e.g., 'mantenimiento-preventivo')",
                unique=True,
            ),
        ),
    ]
