# Generated by Django 5.2.9 on 2026-01-19 01:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_alter_servicephase_slug_alter_servicetype_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phasechannelconfig",
            options={
                "ordering": ["phase__order", "channel"],
                "verbose_name": "Phase Channel Config",
                "verbose_name_plural": "Phase Channel Configs",
            },
        ),
        migrations.CreateModel(
            name="VehiclePhaseConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Orden personalizado para este vehículo"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si esta fase está activa para este vehículo",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Última sincronización desde Core",
                        null=True,
                    ),
                ),
                (
                    "sync_version",
                    models.IntegerField(
                        blank=True,
                        help_text="Versión de sincronización desde Core",
                        null=True,
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        help_text="Fase de servicio (de las fases globales)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_configs",
                        to="notifications.servicephase",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        help_text="Vehículo al que pertenece esta configuración",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_phase_configs",
                        to="notifications.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Phase Config",
                "verbose_name_plural": "Vehicle Phase Configs",
                "db_table": "vehicle_phase_configs",
                "ordering": ["order"],
                "unique_together": {("vehicle", "phase")},
            },
        ),
    ]
